boostcampwm2023/baekjoonrooms

- README.md
> feat/introduce-J139 : 정예찬 자기소개

- README.md
> feat/introduce-J012 : 김기원 자기소개

- README.md
J045 노성주 자기소개를 위한 PR입니다.
앞으로 잘 부탁드려요😊
> feat/introduce-J045 : 노성주 자기소개

- README.md
> feat/introduce-J015 : 김대현 자기소개

- README.md
화요일, 수요일 회의했던 내용 바탕으로 리드미 파일을 정리했습니다.
> feat/edit-readme : 회의 내용 바탕으로 리드미 정리

- client/README.md
- client/src/App.tsx
- client/src/contexts/AuthContext.tsx
- client/src/main.tsx
- client/src/pages/Home.tsx
- client/src/pages/NotFound.tsx
- client/src/routes.tsx
> feat/fe-setting : router, query setting

- extension/background.js
- extension/manifest.json
- extension/popup/popup.css
- extension/popup/popup.html
- extension/popup/popup.js
> feat/extension-setting: 익스텐션 설정

- README.md
> docs: README.md에서 mbti 삭제

- client/.eslintrc.cjs
- client/src/contexts/AuthContext.tsx
ESLint의 옵션값을 수정
https://eslint.org/docs/latest/rules/require-jsdoc
모든 함수에 jsdoc을 요구하는 eslint를 해제
typescript ESLint의 no-explicit-any rule을 충족하기 위해 잠정적 any을 unknown으로 수정
> feat/es-lint-modify : ESLint 관련 수정

- client/.prettierrc
- client/postcss.config.js
- client/prettier.config.cjs
- client/vite.config.ts
prettier-plugin-tailwindcss 가 pretteir.config.cjs 파일로 설정 시 적용이 안되서 파일 삭제 후 .prettierrc 파일에 설정을 추가해주었습니다.
prettier가 적용이 안된 파일들에 prettier를 적용해 주었습니다.
close #40 
- client/prettier.config.cjs
- 설정 변경을 위해 파일 삭제
- client/.prettierrc
- prettier-plugin-tailwindcss 설정 추가
- postcss.config.js
- prettier 적용
- vite.config.ts
- prettier 적용
> feat/prettier-modify: prettier-plugin-tailwindcss 설정 수정

- client/src/contexts/AuthContext.tsx
- client/src/pages/Lobby.tsx
user의 목 데이터를 이용해 로비 페이지 UI를 구성하였습니다.
로그아웃 버튼 클릭 시 Home 페이지로 이동, Create room 버튼 클릭 시 Room 페이지로 이동합니다.
close #46
- client/src/pages/Lobby.tsx
- Lobby 페이지 UI 구성
- client/src/contexts/AuthContext.tsx
- onLogout 함수에 Home 페이지로 이동하는 로직 추가
UI 디자인은 리트룸즈의 디자인과 거의 유사하게 구현했습니다. 이상한 부분 있으면 말해주세요!
https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/74997112/2d5f01b0-8a91-40b4-a841-31b7c862e616
> Feat/lobby/UI: Lobby 페이지 UI

- client/src/contexts/AuthContext.tsx
- client/src/pages/Home.tsx
- client/src/pages/Lobby.tsx
context를 auth와 auth를 update하는 함수를 주입해주는 것으로 변경
> feat: split context

- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/entities/problem.entity.ts
- server/src/entities/room.entity.ts
- server/src/entities/submission.entity.ts
- server/src/entities/tag.entity.ts
- server/src/entities/user.entity.ts
* typeorm으로 엔티티를 생성했습니다. 
* 빠른 개발을 위해 repository level을 둬야하는 data mapper 방식보다는 active record 선택했습니다. 그래서 BaseEntity가 있어요! 
* [erd](https://dbdiagram.io/d/bojrooms-655b10cb3be149578753fa41)를 참고했습니다. 
close #23
> feat/set-db-with-typeorm : typeorm 엔티티 생성

- README.md
리드미 파일 수정했습니다. 다른 수정할 부분 있으면 리뷰달아주세요.
> feat/update-readme: README 파일 수정

- client/src/components/Profile.tsx
- client/src/components/RoomAccessPanel.tsx
- client/src/components/buttons/LogoutButton.tsx
- client/src/components/buttons/RoomCreateButton.tsx
- client/src/components/buttons/RoomJoinButton.tsx
- client/src/pages/Lobby.tsx
로비 페이지의 컴포넌트들을 나누었습니다.
close #68 
- client/src/components/Profile.tsx
- 프로필 컴포넌트 생성
- client/src/components/RoomAccessPanel.tsx
- 룸 접근(생성, 참가) 패널 컴포넌트 생성
- client/src/components/buttons/LogoutButton.tsx
- 로그아웃 버튼 컴포넌트 생성
- client/src/components/buttons/RoomCreateButton.tsx
- 룸 생성 버튼 컴포넌트 생성
- client/src/components/buttons/RoomJoinButton.tsx
- 룸 참가 버튼 컴포넌트 생성
- client/src/pages/Lobby.tsx
- 로비 페이지를 컴포넌트들로 나누기
버튼들은 나중에 각각의 기능들을 추가해주어야 해서 따로 컴포넌트로 다 빼주었는데 이렇게 다 빼는 것이 좋을지 생각해 봐야 할 것 같습니다. 어떻게 하면 좋을지 의견 제시해 주세요.
> feat/lobby-page-components: 로비 페이지 컴포넌트 나누기

- client/src/pages/Home.tsx
- client/tailwind.config.js
tailwind의 color config를 설정했습니다.
> feat/tailwind-color-config: tailwind color config 설정

- .github/workflows/deploy.yml
develop에 pull request를 날리거나 commit을 할 시 자동으로 원격 서버에 배포되도록 actions 설정
> 현재 develop 브랜치에 직접적인 commit은 금지됨.
> ci(deploy.yml): auto deploy 작성

- server/src/entities/user.entity.ts
- server/src/user/user.controller.spec.ts
- server/src/user/user.controller.ts
- server/src/user/user.module.ts
- server/src/user/user.service.spec.ts
- server/src/user/user.service.ts
기존에 존재하던 User entity를 제어하는 Controller와 Service를 추가했습니다.
/user 에 접속하고 body에 {"username": "abcd"} 를 전달하면
abcd라는 이름을 가진 유저가 db에 저장됩니다.
> feat: User Controller / Service 구현 & post를 통한 삽입 테스트 성공

- .github/workflows/deploy.yml
deploy.yml 파일에서
git switch develop이 아니라
git switch origin/{{머지되는 브랜치}}를 통해 테스트해야 한다.
closes #94
> Fix: git actions 이 실패해도 머지되는 버그 수정

- server/src/entities/problem.entity.ts
- server/src/entities/submission.entity.ts
- server/src/entities/tag.entity.ts
- server/src/entities/user.entity.ts
- server/test/app.e2e-spec.ts
프리티어가 120에서 80으로 바뀌었는데 적용이 안된 부분이 있어 에러가 뜨길래 재적용했습니다.
> feat/server-prettier : 프리티어 80 적용

- docker-compose.yml
> DB 포트 빠져있는 거 고침

- client/.dockerignore
- client/Dockerfile
- client/vite.config.ts
- nginx.conf
포트 번호 4173 -> 5173 을 통해
로컬 client에서 npm run dev을 하든
도커 client에서 docker compose up --build client를 하든
똑같은 결과가 나와서 테스트가 용이해집니다!
[client/.dockerignore](https://github.com/boostcampwm2023/web15-BaekjoonRooms/compare/fix/docker?expand=1#diff-76887f59f534794e3609d98a28a8873a5217a54521eaf72a312156de15bc390f)
[client/Dockerfile](https://github.com/boostcampwm2023/web15-BaekjoonRooms/compare/fix/docker?expand=1#diff-c0a19429aa475a5c4fba2e72499771095a4d55a72adf8271238b2a402928b475)
[client/vite.config.ts](https://github.com/boostcampwm2023/web15-BaekjoonRooms/compare/fix/docker?expand=1#diff-ba54b61c10b48d1e2509d8ad3e5a1b0f0cbf878692a21dca8ed3e880850341de)
[nginx.conf](https://github.com/boostcampwm2023/web15-BaekjoonRooms/compare/fix/docker?expand=1#diff-1f91f64bfa3fb0a1ece881887af0a2356b8c529a96fb …
> fix(docker,client): 도커 up된 client가 서버에 접속 못하는 문제 수정

- client/package-lock.json
- client/package.json
- client/src/pages/Room.tsx
- package-lock.json
- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/socket/socket.gateway.ts
- server/src/socket/socket.module.ts
- 패키지 정리
- @Lukaid-dev 님이 추가하신 react socket io connect 코드가 동작하는 데모
- Gateway를 통한 nest의 socket io 지원 코드
> feat(client / server sockets): 웹 소켓 데모 공유

- server/src/entities/problem.entity.ts
- server/src/entities/tag.entity.ts
백준 문제 데이터 삽입을 위해서 엔티티를 아주 약간 수정했습니다. 여기에 index를 더 걸거나 제약 조건을 더 걸어도 dump data 삽입할 때 큰 문제는 없을 것 같긴 한데,,, 잘은 모르겠네요 핳,,,
close #21
> feat/insert-data : 백준 데이터 삽입을 위해 엔티티 약간 수정

- client/src/components/Dropdown.tsx
- client/src/components/MultipleDropdown.tsx
- client/src/components/RoomSettingModal/ProblemList.tsx
- client/src/components/RoomSettingModal/RandomProblem.tsx
- client/src/components/RoomSettingModal/RoomSettingModal.tsx
close #60, close #63, close #64, close #65
커스텀 드롭다운을 구현했습니다
client/src/components/Dropdown.tsx : 1개 고르는 커스텀 드롭다운
client/src/components/MultipleDropdown.tsx : 여러개 고르는 드롭다운
일단 data 가져오는 로직 없이 UI만 구현했습니다.
선택시에 callback 함수들이 선택된 값으로 console.log를 호출하게 했습니다.
ps. 체크 표시에 약간 잔상이 보이는데 캡쳐 문제고 실제 동작에서는 깔끔하게 바뀝니다
> Feat/custom dropdown : 커스텀 드롭다운 구현

- docker-compose.yml
- nginx.conf
* https://osg.kr/archives/2081 여길 참고해서 ssl 인증서를 발급받고 nginx 설정을 했는데 솔직히 잘 했는지는 잘 모르겠습니다
* root 어쩌고,,, 경고때문에 certbot renew 즉 자동 갱신 관련한 건 못했어요,,,ㅜㅠ
close #120
> feat/ssl-setting : https 인증서 설정?  

- server/src/app.module.ts
- server/src/problem/dto/search.problem.dto.ts
- server/src/problem/problem.controller.ts
- server/src/problem/problem.module.ts
- server/src/problem/problem.service.ts
- server/src/room/room.controller.ts
* 문제 검색 api를 만들었습니다.
* 해당 키워드로 시작하는 백준 문제 번호를 가진 문제 또는 백준 문제 이름을 가진 문제를 모두 찾아서 리턴합니다. 
* 해당 키워드로 시작하는 백준 문제 번호를 가져오고 싶었는데 string과 number 간의 type 에러때문에 Raw를 사용했습니다. 다만 보안 상의 문제가 좀 있을 수 있다고는 합니다. 
close #123
1. ![image](https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/71765155/4753ed0c-d9ca-44d9-be1e-06ebd74c25f2)
2. ![image](https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/71765155/e0fa5964-40da-4471-b131-fb1cbfe5739f)
> feat/search-problem : 문제 검색 api

- docker-compose.yml
- server/src/entities/room.entity.ts
- server/src/entities/user.entity.ts
- server/src/room/room.service.ts
* user 하나에 host 하는 룸(과거 hosting한 룸 포함)을 여러개 달 수 있도록 entity를 수정했습니다.
* 잘못된 userId로 create room 하는 경우의 에러를 처리했습니다. 
* docker 내 mysql에서 한글이 깨지는 문제를 docker compose에 command를 넣어 해결했습니다.
> feat/modify-create-room : create room 로직 및 docker compose 수정

- client/src/components/Chat.tsx
- client/src/pages/Room.tsx
기존에 채팅이 비어있으면 줄어드는 현상과 스크롤시 채팅입력창까지 스크롤되던 현상을 변경했습니다.
https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/97015501/8e3bef18-a0d2-4f0f-a058-758767049e81
> feat: 방 채팅 스크롤 수정

- client/src/apis/Auth.ts
- client/src/apis/createRoom.ts
- client/src/apis/joinRoom.ts
- client/src/components/buttons/RoomCreateButton.tsx
- client/src/components/buttons/RoomJoinButton.tsx
- client/src/contexts/AuthContext.tsx
axios 요청 하는 부분을 파일로 빼고 try catch를 다 적용 시켰습니다.
axios 요청 보내는 부분을 다 파일로 뺐습니다.
axios 요청을 받는 부분에 try catch 문을 적용했습니다.
> refactor: axios 부분 수정

- client/src/components/Chat.tsx
- client/src/pages/Room.tsx
chat컴포넌트의 역할을 명확하게 하기위해 소켓연결 로직 분리
> refactor: chat에서 socket연결 로직 분리

- server/src/problem/dto/random.problem.dto.ts
- server/src/problem/problem.controller.ts
- server/src/problem/problem.service.ts
랜덤으로 문제를 검색하는 api를 생성했습니다. 검색 조건은 태그와 난이도, 문제 개수입니다. 태그와 난이도는 쉼표(,)로 구분하며, 최대 count만큼의 문제를 반환합니다. 설정했던 count보다 조회된 문제 수가 적은 경우에 대해서는 프론트 측에서 경고를 주는 방식으로 처리해야 할 것 같습니다. 
close #141
> feat/random-problem : 랜덤 문제 출제 api

- docker-compose.yml
- nginx.conf
초기에 소유자 인증 과정에서만 필요했던 `/var/lib/letsencrypt/` 관련 코드를 제거했습니다. 
close #140
> feat: trim-nginx : 불필요한 nginx 관련 코드 제거

- server/src/roomUser/room.user.service.ts
- server/src/submission/submission.service.ts
> 긴급 패치: roomService 함수의 삭제로 인한 몇몇 에러들 수정

- server/src/room/room.service.ts
> feat/fix-null-error : null 체킹 과정에서 생긴 에러를 length 체크로 변환

- .vscode/settings.json
- client/package-lock.json
- client/package.json
- client/src/components/Chat.tsx
- client/src/components/Message.tsx
- client/src/components/MessageBody.tsx
- client/src/pages/Room.tsx
채팅방에서 코드 마크다운이 사용가능합니다.
dependency :
[react-markdown](https://github.com/remarkjs/react-markdown) : 마크다운을 적용하는 페이지
[react-textarea-autosize](https://github.com/Andarist/react-textarea-autosize) : TextArea 크기 오토 변경
간단해 보이지만 수많은 버그와 사투했습니다...🫠
> Feat/chat markdown : 채팅방 마크다운

- server/src/room/room.service.ts
- server/src/submission/dto/roomSubmission.dto.ts
- server/src/submission/submission.controller.ts
- server/src/submission/submission.module.ts
- server/src/submission/submission.service.ts
scoreboard 노출을 위한 제출 정보 api를 만들었습니다. groupby를 지원하는 typeorm 메서드가 별로도 없어 쿼리빌더를 사용했습니다. 
close #185
> feat/scoreboard-api : 스코어보드 노출을 위한 제출 정보 api

- client/src/apis/randomProblems.ts
- client/src/apis/searchProblem.ts
- client/src/components/Lobby/ThemeSettingModal.tsx
- client/src/components/Room/Problems.tsx
- client/src/components/Room/RoomSettingModal/ProblemList.tsx
- client/src/components/Room/RoomSettingModal/RandomProblem.tsx
- client/src/components/Room/RoomSettingModal/RoomSettingModal.tsx
- client/src/components/Room/RoomSettingModal/SearchResults.tsx
- client/src/components/Room/RoomSettingModal/SelectProblem.tsx
- client/src/components/buttons/StartButton.tsx
- client/src/contexts/RoomProvider.tsx
- client/src/types/Problem.ts
- client/src/types/ProblemType.ts
- client/src/types/RoomInfoType.ts
- client/src/util/goSolveProblem.ts
ProblemResponse와 ProblemType이 나뉘어있던 것을 하나로 통합했습니다. 다른 피쳐 개발 중에 고친거라 조금 상관없는 코드가 있긴한데, 빠르게 머지해주시면, 이어서 작업 빠르게 하겠씁니다.
> refactor: problem type을 통일했습니다

- client/src/components/Room/Message.tsx
> feat/message-ui-refactoring: 메세지 컴포넌트 ui 수정

- client/src/pages/PrivacyPolicy.tsx
- client/src/routes.tsx
개인정보 보호 페이지 추가
[baekjoonrooms.com/privacyPolicy](https://baekjoonrooms.com/privacyPolicy)
> feat: 개인정보 보호정책 페이지 추가

- server/src/socket/socket.gateway.ts
- server/src/socket/socket.service.ts
- server/src/types/MessageInterface.ts
- ChatEvent.Wrong 추가 및 문제 틀렸을 때 보내주기
- MessageInterface에서 color 삭제
> Hotfix(MessageInterface): ChatEvent.Wrong 보내주기 

- server/src/app.controller.ts
- server/src/types/userSession.ts
기원님의 요청대로 /session 요청에 isHost를 추가했습니다.
> feat(UserSession): isHost 추가

- client/src/apis/joinRoom.ts
joinRoom.ts 에서 throw error를 안해줘서 존재하지 않는 방에 참가 시 alert를 안해주던 버그를 고쳤습니다.
> hotfix/no-room-alert: 존재하지 않는 방에 참가 시 alert를 안해주던 버그 고침

- extension/background.js
- extension/manifest.json
팝업의 토글 버튼 클릭 시 on/off 전환이 안되던 문제를 해결했습니다.
> feat/extension-toggle-button-fix: 토글 버튼 클릭 시 on/off 전환이 안되는 문제 해결

- README.md
> feat/update-readme: 리드미 파일 업데이트

- README.md
목요일 말씀드린대로 사진을 추가해봤습니다.
처음에는 맨 위에 추가했다가, 간단한 설명글 다음에 사진이 나오는 게 더 이쁠 것 같아 위치를 조정했습니다.
> docs(readme): 리드미에 사진 추가

- README.md
> docs(readme): dqgthb -> vimkim

- .github/workflows/cicd.yml
> hotfix: cicd.yml github actions from develop to main branch

- .github/workflows/cicd.yml
develop -> main in sh deploy script
> hotfix: develop -> main in deploy

- server/Dockerfile
start:prod -> prod 로 고쳐 배포가 안 되는 현상을 수정했습니다.
> npm run start:prod -> prod

- server/package-lock.json
- server/package.json
- server/src/app.module.ts
- server/src/auth/auth.module.ts
- server/src/common/exception.filter.provider.ts
- server/src/common/exception.filter.ts
- server/src/common/middleware/session.ts
- server/src/common/validation.pipe.ts
- server/src/logger/custom.logger.ts
- server/src/logger/logger.module.ts
- server/src/main.ts
- server/src/socket/socket.adapter.ts
- server/test/app.e2e-spec.ts
- server/tsconfig.json
프로젝트의 자동화를 위한 작동하는 e2e 테스트 작성: 프로젝트의 품질을 보장하기 위해 e2e(end-to-end) 테스트가 작성되었습니다. 이는 CI/CD 파이프라인에서 테스트 자동화의 기반을 마련합니다.
전역 설정을 main.ts에서 app.module.ts로 이동: 보다 나은 e2e 테스트를 위해, main.ts 파일에 정의된 전역 설정들이 app.module.ts로 옮겨졌습니다. 이는 애플리케이션의 설정과 초기화 코드를 모듈화하여 관리하기 용이합니다.
- Passport
- 전역 예외 필터: 
- 전역 검증 파이프 
- 커스텀 로거
app.module.ts로 옮기려 했으나 구조 상 시도 실패. 
Redis와 세션 관리를 위한 미들웨어 생성 과정이 재구성되었습니다. 이는 코드의 가독성과 유지 보수성을 향상시킵니다.
기타:
Synthetic Default Import 허용: 프로젝트 설정에서 synthetic default import를 허용하여, 모듈 가져오기 시 default import 문법을 사용할 수 있게 되었습니다. 이는 특히 ES 모듈과의 호환성을 개선합니다.
이 PR은 프로젝트의 설정, 모듈성, 테스트 자동화 등 여러 측면에서 중요한 개선을 제공합니다.
> server E2E test 기반 테스트 작성 및 동작 확인 성공

- .github/workflows/cicd.yml
> Temporarily disable CD github actions until server migration

- README.md
> docs(readme): change github name dqgthb -> vimkim
