boostcampwm2023/baekjoonrooms

- client/public/mocks/User.json
- client/src/App.tsx
- client/src/apis/Auth.ts
- client/src/contexts/AuthContext.tsx
- client/src/pages/Home.tsx
- client/src/pages/Lobby.tsx
- client/src/pages/ProtectedRoute.tsx
- client/src/pages/Room.tsx
- client/src/routes.tsx
- client/src/types/UserType.ts
router를 수정하고, 로그인을 하지 않으면 다음 페이지로 넘어갈 수 없도록 Protected Router를 설정했습니다.
close #38 
- client/src/App.tsx
- AuthProvider에 value를 넘겨줄 필요가 없도록 수정
- client/src/apis/Auth.ts
- 임시로 login api작성
- client/src/contexts/AuthContext.tsx
- context자체에서 api를 요청하여 유저 정보를 받아오도록 하였고, 추후에 로그인이 되었을 때 useEffect를 다시 부르도록 의존성 배열을 추가하거나, 아예 다른 방향으로 수정하는 것도 생각중입니다. (의견 제시해 주십셔)
- client/src/pages/Home.tsx
- 임시 home count로 리렌더 되어도 그 윗단의 Provider에서 useEffect가 다시 안불리는거 확인용으로 달아둠
- client/src/pages/Lobby.tsx
- 임시 로비
- client/src/pages/ProtectedRoute.tsx
- 로그인 가드 역할. 로그인을 하지 않아 user정보가 없을 시 home으로 redirect
- client/src/pages/Room.tsx
- 임시 방
- client/src/routes.tsx
- 수정된 router. ProtectedRoute된 컴포넌트 하위의 children은 모두 보호가 되는 것으로 확인함. (확실하지 않음 더 알아봐야 함)
- client/src/types/UserType.ts
- 오늘 논의한 내용을 바탕으로 User 데이터 정의
아직 여러가지로 …
> feat/router-context-setting: Router 및 Protected Router 설정

- client/src/pages/RoomSetting.tsx
- client/src/routes.tsx
방 옵션을 설정하는 창의 UI를 구성하였습니다.
방 옵션 설정 창은 직접 문제 출제와 랜덤 문제 출제 설정 창이 있습니다.
일단 /roomsetting 페이지에 두 가지 창 UI를 구현해 놓았습니다.
close #44 
close #48 
- client/src/pages/RoomSetting.tsx
- 룸 설정 창 UI 구성
- client/src/routes.tsx
- /roomsetting 경로로 RoomSetting 페이지 라우터 설정
룸 설정 창은 페이지로 구현하는 것이 아니라 컴포넌트로 구현되어야 할 것 같습니다.
룸 페이지가 구성되면 룸 페이지에서 룸 설정 버튼 클릭 시 룸 페이지 내에서 룸 설정 창이 나오도록 하면 좋을 것 같습니다.
최대 문제 갯수나 랜덤 문제 출제 시 태그를 선택하는 것도 어떤 식으로 할지 의논해봅시다.
https://github.com/boostcampwm2023/web15-BaekjoonRooms/assets/74997112/8205ce5d-2f82-4711-b787-5f8815b2aab1
> Feat/room setting/UI: 방 설정 창 UI

- .env
- docker-compose.yml
docker-compose.yml에 들어있는 유저 정보, 비밀번호, 포트 번호와 같은 정보들을 .env로 추출했습니다.
일단 로컬에서 돌리려면
```bash
set -a; source ../.env; set +a && export DB_HOSTNAME=localhost && npm start
```
하면 잘 돌아갑니다!
로컬에서 잘 동작하는 모습입니다.
closes #54
> chore: docker-compose 파일에 민감한 정보 .env 파일로 추출하기

- docker-compose.yml
#71 에서 최상위 .env를 지웠고,
```
env_file:
- ./.env -> -./server/.env
```
대신 각 프로젝트 디렉토리의 .env를 사용하도록 변경합니다.
용이한 테스트 및 로컬 개발 환경을 위해서 server / client의 .env를 분리했습니다.
또한 server에 추가로 environment: DB_HOSTNAME=mysql을 추가해 .env를 덮어씌우도록 설정합니다.
```sh
docker compose up --build # DB_HOSTNAME=mysql
npm start # DB_HOSTNAME=localhost
```
자동으로 실행 환경에 맞게 DB_HOSTNAME을 변경할 수 있습니다.
> fix(docker-compose.yml): .env -> ./server/.env

- docker-compose.yml
- nginx.conf
nginx를 이용한 리버스 프록싱을 통해 baekjoonrooms.com은 4173 포트로, api.baekjoonrooms.com은 4000 포트로 이어지도록 변경합니다. 
close #85
> feat/nginx : 리버스 프록싱을 통한 서브도메인 별 다른 포트 적용

- server/.prettierrc
prettierrc 1줄 수정
이유: 모니터 양쪽에 파일 2개 띄워두고 서로 비교하면서 코딩할 때 80이 가장 적절하다고 느꼈습니다.
> style(prettier): :art: server prettier 줄 너비 120 -> 80

- client/src/components/ScoreBoardModal/Players.tsx
- client/src/components/ScoreBoardModal/Result.tsx
- client/src/components/ScoreBoardModal/ScoreBoard.tsx
- client/src/components/ScoreBoardModal/ScoreBoardModal.tsx
- client/src/routes.tsx
스코어보드 모달창 UI를 만들었습니다.
client/public/mocks/Scores.json : ScoreBoard Mock data
client/src/components/ScoreBoardModal/\*.tsx : 스코어보드 UI
client/src/routes.tsx : 임시 라우터 추가, 추후 모달화 되면 삭제
client/src/types/ScoreType.ts : 점수 타입 선언
초록색 체크가 좀 안보이는 거 같은데 배경색이나 초록색 중 하나를 바꾸면 좋을 것 같네요
> Feat/scoreboard/UI : ScoreBoard UI

- .vscode/settings.json
- client/package-lock.json
- client/package.json
- client/src/components/RoomInfo.tsx
- client/src/components/ScoreBoardModal/ScoreBoardModal.tsx
- client/src/components/buttons/ExitButton.tsx
- client/src/components/buttons/ScoreBoardButton.tsx
close #90
룸 페이지의 기능들을 추가했습니다.
- react-toastify dependency 추가
- client/src/components/RoomInfo.tsx : 룸 페이지 방 코드 복사 하기
- client/src/components/buttons/ExitButton.tsx : 나가기 버튼 로직
- client/src/components/ScoreBoardModal/ScoreBoardModal.tsx : 스코어보드 모달화
> Feat/room/logic : 룸 페이지 로직 추가

- server/src/app.module.ts
- server/src/entities/room.entity.ts
- server/src/room/dto/create.room.dto.ts
- server/src/room/room.controller.ts
- server/src/room/room.module.ts
- server/src/room/room.service.ts
- server/src/user/user.controller.ts
- server/src/user/user.service.ts
1. 방 생성 api를 만들었는데 개발의 편의를 위해 아직 auth 데코레이터는 붙이지 않았습니다.
2. 방 생성 api의 경우, user가 참여하고 있는 방이 있다면 400에러를 띄우고 아니면 참여한 룸의 정보를 일단 모두 보여줍니다.
3. 코드는 username과 현재 시각을 해시한 값의 첫 6자리를 가져옵니다. 코드의 충돌을 최소화하기 위해 해시를 사용했습니다. 
4. 코드같은 경우 혹시 모를 중복을 피하기 위해, 방 종료 시 코드 정보를 삭제해야 할 지도 모르겠습니다.
5. 중간에 entity의 nullable 관련 설정을 약간 수정하였습니다. 
close #118
> feat/create-room : 방 생성 API

- server/src/entities/room.entity.ts
- server/src/entities/roomUser.entity.ts
- server/src/entities/user.entity.ts
- server/src/room/room.module.ts
- server/src/room/room.service.ts
- server/src/roomUser/room.user.module.ts
- server/src/roomUser/room.user.service.ts
- server/src/types/roomUser.ts
- server/src/user/user.service.ts
1. user와 room 사이의 many to many 관계를 데코레이터를 이용하지 않고 user와 RoomUser간에 또 room과 RoomUser간에 관계를 만들어서 생성했습니다.
2. pk를 room과 user id의 복합키로 만들고 싶었으나 쉽지 않았던 관계로 별도의 pk를 생성했고 복합키는 index로 걸어두었습니다.
3. entity 변경의 결과로 user service와 room service의 로직을 일부 변경하였으며, roomUser 모듈을 별도로 추가하였습니다.
close #138 
생성된 room user 디비는 다음과 같습니다.
> feat/change-user-room-relation : user와 room 사이에 many to many 관계 추가

- extension/background.js
- extension/scripts/content.js
- 방 참가 여부에 따라 활성화 비활성화 되는 부분 로직에 문제가 있어 조금 수정했습니다.
- 로컬에서 테스트를 할때마다 url들을 바꿔줘야 해서 미리 remote용 local용 url을 지정해 놓은 후 주석 처리 해 놓았습니다.
- contents.js의 urlPattern과 background.js의 BASE_URL을 테스트 하는 곳에 맞게 바꿔주면 됩니다.
- manifest.json에서는 변수 사용과 주석처리가 안되서 직접 바꿔주면 됩니다.
- "host_permissions"과 "content_scripts"의 "matches" url을 바꾸면 됩니다.
- 총 4 부분을 바꿔주어야 잘 동작합니다.
> feat:extension-refactoring: 익스텐션 버그 수정, 로컬 테스트를 위한 코드 수정

- server/src/entities/room.entity.ts
- server/src/entities/user.entity.ts
- server/src/room/room.module.ts
- server/src/room/room.service.ts
- server/src/socket/socket.gateway.ts
- server/src/socket/socket.module.ts
- server/src/socket/socket.service.ts
- server/src/submission/submission.service.ts
- server/src/types/MessageInterface.ts
- server/src/types/RoomInfo.ts
- 길어진 SocketGateway 코드를 SocketService로 분리
- 공식 문서를 참고하여 afterInit으로 SocketService에 server 주입했습니다.
- 소켓과 http 분리
- socket connect와 http create / join
- socket disconnect와 http exit 차이점 명확하게 분리
> feat(socketService): 소켓 서비스 추가 

- server/src/problem/problem.service.ts
- server/src/socket/socket.service.ts
위 에러를 해결했습니다..
다이내믹 쿼리는 안 쓰는 게 좋다는 교훈을 얻었습니다.
빠른 테스트를 위해 포문 돌렸습니다...
> hotfix(dynamic-query): dynamic  쿼리 제거

- client/src/components/buttons/ScoreBoardButton.tsx
스코어보드 버튼을 시작을 눌러야 보이게 헀습니다.
roomInfo의 isStarted가 참일 때만 보입니다.
이렇게 하면 roomInfo가 무조건 있는 상태에서만 확인할 수 있어서 404에러가 보이지 않을 것 같습니다.
room-info 소켓 버그 해결 후 테스트 가능합니다.
> hotfix: 스코어보드 시작 버튼 눌러야 보이게

- server/src/submission/submission.controller.ts
- server/src/submission/submission.service.ts
- submission.service.ts:
기존에는 유저가 언제 어떤 문제를 제출해도 모두 디비에 반영이 되고 웹소켓을 통해 안내 메세지가 뿌려졌습니다.
이제 다음과 같은 경우 submission이 거절됩니다.
- 방이 시작되지 않았을 때
- 방이 끝났을 때
- 방장이 출제한 문제가 아닐때
구현이 간단해서 게임이 끝났을 때 아예 제출을 막는 방식으로 했는데,
빠른 시일 내에 기존 기획대로 게임이 끝나도 문제는 계속 제출할 수 있게 수정할 예정입니다.
> feat(submission-reject): 방이 시작되지 않았거나, 종료되었거나, 출제되지 않은 문제를 제출하면 거부한다.

- server/src/auth/auth.service.ts
- server/src/entities/room.entity.ts
- server/src/entities/submission.entity.ts
- server/src/entities/user.entity.ts
- server/src/problem/problem.module.ts
- server/src/problem/problem.service.ts
- server/src/room-user/room-user.entity.ts
- server/src/room-user/room-user.module.ts
- server/src/room-user/room-user.service.ts
- server/src/room/room.module.ts
- server/src/room/room.service.ts
- server/src/socket/socket.gateway.ts
- server/src/socket/socket.module.ts
- server/src/socket/socket.service.ts
- server/src/submission/submission.module.ts
- server/src/submission/submission.service.ts
- server/src/types/room-user-input.ts
- server/src/user/user.service.ts
- server/tsconfig.json
- 본 커밋은 #241 와 연결된 작업입니다.
- 모든 임포트 경로가 "src/ ... " 등의 tsconfig baseUrl 상 절대 경로로 잘못 리펙토링된 점을 수정했습니다.
- tsconfig.json에서 baseUrl을 삭제했습니다.
절대 경로의 문제점: 추가적인 설정 없이는 jest와 같은 외부 툴을 실행하기 어렵습니다.
> refactor(*,-tsconfig): baseUrl 제거하고 모듈 임포트 상대 경로로 통일하기

- extension/README.md
익스텐션 리드미 파일 초안 작성했습니다.
추가하거나 수정할 사항 있으면 얘기해 주세요.
close #245
> feat/create-extension-readme-file: extension readme

- .github/workflows/cicd.yml
```
if: github.event_name == 'push' && github.ref == 'refs/heads/main'
```
추가를 통해 풀리퀘 어셉될 시에만 cd 실행
스킵이 잘됨
> restrict cicd to work only when pull request is merged

- server/src/auth/auth.service.ts
- server/src/common/middleware/session.ts
- server/src/problem/problem.service.ts
- server/src/room/room.service.ts
- server/src/socket/socket.gateway.ts
- server/src/socket/socket.service.ts
- server/src/submission/submission.service.ts
- server/src/user/user.service.ts
모든 == null 비교 연산을 피드백을 통해
조금 더 명시적인 isNil 함수로 통일했습니다.
> replace all == null (google style) to isNil for clarity

- server/src/logger/morgan.ts
- server/src/main.ts
- server/src/socket/socket.adapter.ts
- server/tsconfig.json
tsconfig의 타입 체킹을 강화하고,
main.ts 의 morgan,
socket.adapter.ts의 wrap 함수에 있던 implicitAny를 삭제했습니다.
> fix main, morgan implicit any

- server/src/entities/submission.entity.ts
- server/src/room/room-code/room-code.pipe.spec.ts
- server/src/room/room-code/room-code.pipe.ts
- server/src/room/room.controller.ts
- server/src/room/room.service.ts
- server/src/submission/submission.service.ts
간단한 유닛 테스트만 하고 통합 테스트 X. 프론트와 함께 할 예정. @glowisn 
```ts
/**
* returns an array of user id, username, and the number of accepted problems of the user, sorted by the number of accepted problems
* @param code
*/
async getRoomRankings(code: string) {
Submission;
User;
const qb = this.roomRepository
.createQueryBuilder('room')
.where('room.code = :code', { code })
.innerJoin('room.joinedUsers', 'roomUser')
.innerJoin('roomUser.user', 'user')
.innerJoin(
'room.submissions',
'submission',
'submission.status = :status AND submission.user_id = user.id AND submission.alreadyAccepted = false',
{
status: Status.ACCEPTED,
},
)
.select('user.id', 'userId')
.addSelect('user.username', 'username')
.addSelect('COUNT(submission.id)', 'acceptedCount')
.addSelect('MAX(submission.submittedAt)', …
```
> 289 fix ranking api not working
